version: 2
jobs:
  test:
    docker:
      - image: python:3.6.8
    steps:
      - checkout
      - run:
          name: Install dependency
          command: pip install pycodestyle
      - run:
          name: Check by pycodestyle
          command: pycodestyle *.py
  review:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Install heroku cli
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Update ACCESS TOKEN
          command: |
            heroku config:set -a kimetaro-pr-23 ACCESSTOKEN="${ACCESSTOKEN_DEV_1}"
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - review:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
